name: Build Artifacts

on:
  workflow_dispatch:
    inputs:
      linux:
        description: "Build for Linux"
        type: boolean
        default: true
      windows:
        description: "Build for Windows"
        type: boolean
        default: true
      macos:
        description: "Build for macOS"
        type: boolean
        default: true

jobs:
  build-linux:
    if: ${{ github.event.inputs.linux == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            dist/release/*.AppImage
            dist/release/*.deb
          if-no-files-found: error

  build-windows:
    if: ${{ github.event.inputs.windows == 'true' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/release/*.exe
          if-no-files-found: error

  build-macos:
    if: ${{ github.event.inputs.macos == 'true' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/release/*.dmg
          if-no-files-found: error
